# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alex Jerome
email: ""
description: > # this means to ignore newlines until "baseurl:"
 I'm a Marketing major and a Computer Science minor at the University of Maryland, College Park.
 I'm known for my work at R2integrated, Mindgrub, RedBlack Consulting and Bitcamp.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alexejero.me" # the base hostname & protocol for your site
twitter_username: AlexEJerome
github_username:  AlexEJerome

# Build settings
markdown: kramdown
